DEFRA/ffc-demo-calculation-service

README.md
azure-pipelines.yaml
docker-compose.local.yaml
docker-compose.override.yaml
docker-compose.test.yaml
docker-compose.yaml
helm/production-values.yaml
helm/values.yaml
package.json
scripts/deploy
scripts/start
scripts/stop
scripts/test

Rename Helm, script, build and docker-compose values from "mine-support" to "ffc-demo"
https://eaflood.atlassian.net/browse/FPD-527
https://eaflood.atlassian.net/browse/FPD-534
https://eaflood.atlassian.net/browse/FPD-520
https://eaflood.atlassian.net/browse/FPD-514

Rename core values

---

README.md
docker-compose.local.yaml
docker-compose.override.yaml
docker-compose.yaml
scripts/connected-start
scripts/connected-stop
scripts/send-test-message
scripts/start
scripts/stop
scripts/testEnv
server/services/message-service.js
server/services/messaging/message-sender.js
test/send-test-message.js

https://eaflood.atlassian.net/browse/FPD-480
Default to isolated start/stop and provide additional scripts for
running this service alongside others in the Mine Support stack.

Clarify start/stop scripts

---

README.md

Must have been copied in from another repo by mistake.

Remove erroneous example from Readme

---

scripts/exec
scripts/helm/install
scripts/start
scripts/stop
scripts/test

https://eaflood.atlassian.net/browse/PSD-120

Refactor scripts in line with other FFC demo repos

---

azure-pipelines.yaml
docker-compose.test.yaml
scripts/test

https://eaflood.atlassian.net/browse/PSD-194

Isolate tests from running service

---

Jenkinsfile
helm/ffc-demo-calculation-service/jenkins-aws.yaml

https://eaflood.atlassian.net/browse/PSD-177

Build Jenkins build pipeline for ffc-demo-calculation-service

---

Jenkinsfile
azure-pipelines.yaml
docker-compose.link.yaml
docker-compose.override.yaml
docker-compose.test.yaml
docker-compose.yaml
package.json
scripts/start
scripts/test

https://eaflood.atlassian.net/browse/PSD-196

Isolate tests from host environment

---

Jenkinsfile

https://eaflood.atlassian.net/browse/PSD-231
Use a unique value for the redeployOnChange annotation to trigger pod
redeployment in Kubernetes on each deployment from the Jenkins build
pipeline.

Roll pods on every deployment from build pipeline

---

helm/ffc-demo-calculation-service/templates/deployment.yaml

https://eaflood.atlassian.net/browse/PSD-315

Quoted all values as per Helm best practice advice

---

Jenkinsfile
package-lock.json

https://eaflood.atlassian.net/browse/PSD-414

Add SonarQube integration

---

README.md

https://eaflood.atlassian.net/browse/PSD-418

Remove ADO badge

---

server/services/calculations/gross.js

https://eaflood.atlassian.net/browse/PSD-446

Fix code smell in gross calculation

---

Jenkinsfile
package.json

https://eaflood.atlassian.net/browse/PSD-488

Add versioning to Jenkinsfile

---

Jenkinsfile
package.json

https://eaflood.atlassian.net/browse/PSD-504

Services should be isolated by folder in Jenkins

---

Jenkinsfile
docker-compose.yaml
package.json

https://eaflood.atlassian.net/browse/PSD-539

Update pipeline for move to Non Production

---

helm/ffc-demo-calculation-service/templates/deployment.yaml
helm/ffc-demo-calculation-service/values.yaml
package.json

https://eaflood.atlassian.net/browse/PSD-532

Psd 532 pod priority

---

Jenkinsfile
helm/ffc-demo-calculation-service/templates/deployment.yaml
helm/ffc-demo-calculation-service/templates/labels.yaml
helm/ffc-demo-calculation-service/values.yaml
package.json

https://eaflood.atlassian.net/browse/PSD-530

PSD 530 K8S labels

---

Jenkinsfile
README.md
docker-compose.yaml
helm/ffc-demo-calculation-service/templates/deployment.yaml
helm/ffc-demo-calculation-service/templates/service-account.yaml
helm/ffc-demo-calculation-service/values.yaml
package.json
server/config/mq-config.js

https://eaflood.atlassian.net/browse/PSD-570

The demo service should use service accounts for SQS

---

Jenkinsfile
package.json

https://eaflood.atlassian.net/browse/PSD-793
Check merge to master with updated jenkins lib

Check Jenkins pipeline with Helm chart repo env

---

Jenkinsfile
helm/ffc-demo-calculation-service/deployment-config-keys.txt
helm/ffc-demo-calculation-service/templates/config-map.yaml
helm/ffc-demo-calculation-service/templates/container-secret.yaml
helm/ffc-demo-calculation-service/templates/eks-service-account.yaml
helm/ffc-demo-calculation-service/values.yaml
package.json

https://eaflood.atlassian.net/browse/PSD-843

Psd 843 keyvault

---

README.md
docker-compose.yaml
helm/ffc-demo-calculation-service/templates/config-map.yaml
helm/ffc-demo-calculation-service/templates/container-secret.yaml
helm/ffc-demo-calculation-service/values.yaml
index.js
jest.config.js
package-lock.json
package.json
server/services/app-insights.js

https://eaflood.atlassian.net/browse/PSD-821

Integrate App Insights

---

helm/ffc-demo-calculation-service/templates/developer-rolebinding.yaml
package.json

https://eaflood.atlassian.net/browse/PSD-692

Rolebinding only on PR deployment

---

jsconfig.json
package-lock.json
package.json

- chore: increment version
- chore: increment version
- feat: ignore node_modules to maintain performance

House keeping

---

package.json
provision.azure.yaml

https://eaflood.atlassian.net/browse/PSD-929

Add Azure manifest

---

README.md
docker-compose.test.yaml
docker-compose.yaml
jest.config.js
jest.setup.js
package-lock.json
package.json
server/services/messaging/message-base.js
server/services/messaging/message-receiver.js
test/integration/local/message-receiver.test.js

https://eaflood.atlassian.net/browse/PSD-956

Run all tests

---

Dockerfile
package-lock.json
package.json

https://eaflood.atlassian.net/browse/PSD-1009

Update parent image to one with CA cert

---

package-lock.json
package.json
server/services/app-insights.js

https://eaflood.atlassian.net/browse/PSD-924

Log when App Insights is active

---

helm/ffc-demo-calculation-service/templates/_container.yaml
package-lock.json
package.json

https://eaflood.atlassian.net/browse/PSD-1109

App insights requires writable volume

---

package-lock.json
package.json

This pr includes the below changes to update dependent packages to the latest version
https://dev.azure.com/defragovuk/DEFRA-FFC/_workitems/edit/231573

231573: Updating dependency packages

---

.azuredevops/build.yaml
helm/ffc-demo-calculation-service/Chart.yaml
helm/ffc-demo-calculation-service/templates/_container.yaml
helm/ffc-demo-calculation-service/templates/config-map.yaml
helm/ffc-demo-calculation-service/templates/container-secret.yaml
helm/ffc-demo-calculation-service/templates/deployment.yaml
helm/ffc-demo-calculation-service/templates/developer-rolebinding.yaml
helm/ffc-demo-calculation-service/templates/horizontal-pod-autoscaler.yaml
helm/ffc-demo-calculation-service/values.yaml
package-lock.json
package.json

This pr includes the changes to update helm charts for ADP and added ADO build pipeline.
https://dev.azure.com/defragovuk/DEFRA-FFC/_workitems/edit/231730

213730: Updated helm charts for ADP and added ADO build pipeline

---

appConfig/appConfig.snd2.json
appConfig/appConfig.snd3.json
package-lock.json
package.json

This PR contains the changes for app config for snd2 and snd3.
[AB#262177](https://dev.azure.com/defragovuk/93c65135-d16b-49d6-a191-4a5313532779/_workitems/edit/262177)

262177: updated app config and package

---

appConfig/appConfig.dev1.json
appConfig/appConfig.tst1.json
package-lock.json
package.json

Added Dev and Tst config file for ffc-demo-calculation-service

261316: Added Dev and Tst config file 

---

package.json

[AB#268744](https://dev.azure.com/defragovuk/93c65135-d16b-49d6-a191-4a5313532779/_workitems/edit/268744)

268744: enable coverage

---

helm/ffc-demo-calculation-service/values.yaml
package-lock.json
package.json

Removed duplicate values defined in the values.yaml files.   Also removed values which are the same as the defaults in the helm-library.
Information defined in the app config files will not be duplicated in the values.yaml file
Tested changes against SND1 Cluster and Demo Apps are still working successfully.

277457: Remove duplicate values defined in the values.yaml files for each repo

---

README.md
helm/ffc-demo-calculation-service/values.yaml
package-lock.json
package.json

Helm cleanup and Readme updates

Helm cleanup and Readme updates

---

.azuredevops/build.yaml
package.json

*A brief description of changes being made*
*Link to the relevant work items: 
[AB#323021](https://dev.azure.com/defragovuk/93c65135-d16b-49d6-a191-4a5313532779/_workitems/edit/323021)
Simplify the variable import from variable groups specific to environment
*Any specific actions or notes on review?*
*Any relevant testing information and pipeline runs.*
https://dev.azure.com/defragovuk/DEFRA-FFC/_build/results?buildId=498913&view=results
Have you updated any related templates, repositories or dependencies for new changes? We must ensure any dependencies like Software Templates are updated to include the latest changes to be scaffolded for all services where applicable.

323021: Variable Import 

---

.pre-commit-config.yaml
appConfig/appConfig.prd1.yaml
appConfig/appConfig.pre1.yaml
appConfig/appConfig.tst2.yaml
package.json
pull_request_template.md

- Added PRE and PRD config files
- Also added TST2 config files (TST2 will be set up later)
- Add PR Template to align with the new repositories created by the ADP Scaffolders.
Related Work Items [AB#259852](https://dev.azure.com/defragovuk/93c65135-d16b-49d6-a191-4a5313532779/_workitems/edit/259852)    [AB#338671](https://dev.azure.com/defragovuk/93c65135-d16b-49d6-a191-4a5313532779/_workitems/edit/338671)

259852: Added PRE and PROD Configuration
